JsonCpp - JSON data format manipulation library
JsonCpp project page JsonCpp home page
Json::ValueIteratorBase Class Reference
base class for Value iterators.
#include <json/value.h>
Inherited by Json::ValueConstIterator, and Json::ValueIterator.
Public Types
typedef unsigned int size_t
typedef int difference_type
typedef ValueIteratorBase SelfType
Public Member Functions
ValueIteratorBase ()
ValueIteratorBase (const ValueInternalArray::IteratorState &state)
ValueIteratorBase (const ValueInternalMap::IteratorState &state)
bool operator== (const SelfType &other) const
bool operator!= (const SelfType &other) const
difference_type operator- (const SelfType &other) const
Value key () const
Return either the index or the member name of the referenced value as a Value.
UInt index () const
Return the index of the referenced Value. -1 if it is not an arrayValue.
const char * memberName () const
Return the member name of the referenced Value. "" if it is not an objectValue.
Protected Member Functions
Value & deref () const
void increment ()
void decrement ()
difference_type computeDistance (const SelfType &other) const
bool isEqual (const SelfType &other) const
void copy (const SelfType &other)
Detailed Description
base class for Value iterators.
Definition at line 913 of file value.h.
Member Typedef Documentation
typedef int Json::ValueIteratorBase::difference_type
Reimplemented in Json::ValueConstIterator, and Json::ValueIterator.
Definition at line 917 of file value.h.
typedef ValueIteratorBase Json::ValueIteratorBase::SelfType
Reimplemented in Json::ValueConstIterator, and Json::ValueIterator.
Definition at line 918 of file value.h.
typedef unsigned int Json::ValueIteratorBase::size_t
Reimplemented in Json::ValueConstIterator, and Json::ValueIterator.
Definition at line 916 of file value.h.
Constructor & Destructor Documentation
Json::ValueIteratorBase::ValueIteratorBase ()
Definition at line 18 of file json_valueiterator.inl.
Json::ValueIteratorBase::ValueIteratorBase (const ValueInternalArray::IteratorState & state)
Definition at line 40 of file json_valueiterator.inl.
Json::ValueIteratorBase::ValueIteratorBase (const ValueInternalMap::IteratorState & state)
Definition at line 47 of file json_valueiterator.inl.
Member Function Documentation
ValueIteratorBase::difference_type Json::ValueIteratorBase::computeDistance (const SelfType & other) const [protected]
Definition at line 94 of file json_valueiterator.inl.
References array_, and map_.
Referenced by operator-().
void Json::ValueIteratorBase::copy (const SelfType & other) [protected]
Definition at line 148 of file json_valueiterator.inl.
References array_, and map_.
Referenced by Json::ValueIterator::operator=(), and Json::ValueConstIterator::operator=().
void Json::ValueIteratorBase::decrement () [protected]
Definition at line 81 of file json_valueiterator.inl.
Referenced by Json::ValueIterator::operator--(), and Json::ValueConstIterator::operator--().
Value & Json::ValueIteratorBase::deref () const [protected]
Definition at line 55 of file json_valueiterator.inl.
Referenced by Json::ValueIterator::operator*(), and Json::ValueConstIterator::operator*().
void Json::ValueIteratorBase::increment () [protected]
Definition at line 68 of file json_valueiterator.inl.
Referenced by Json::ValueIterator::operator++(), and Json::ValueConstIterator::operator++().
UInt Json::ValueIteratorBase::index () const
Return the index of the referenced Value. -1 if it is not an arrayValue.
Definition at line 185 of file json_valueiterator.inl.
bool Json::ValueIteratorBase::isEqual (const SelfType & other) const [protected]
Definition at line 131 of file json_valueiterator.inl.
References array_, and map_.
Referenced by operator!=(), and operator==().
Value Json::ValueIteratorBase::key () const
Return either the index or the member name of the referenced value as a Value.
Definition at line 161 of file json_valueiterator.inl.
References memberName().
Referenced by memberName().
const char * Json::ValueIteratorBase::memberName () const
Return the member name of the referenced Value. "" if it is not an objectValue.
Definition at line 201 of file json_valueiterator.inl.
References key().
Referenced by key().
bool Json::ValueIteratorBase::operator!= (const SelfType & other) const [inline]
Definition at line 933 of file value.h.
References isEqual().
difference_type Json::ValueIteratorBase::operator- (const SelfType & other) const [inline]
Definition at line 938 of file value.h.
References computeDistance().
bool Json::ValueIteratorBase::operator== (const SelfType & other) const [inline]
Definition at line 928 of file value.h.
References isEqual().
Member Data Documentation
ValueInternalArray::IteratorState Json::ValueIteratorBase::array_
Definition at line 973 of file value.h.
Referenced by computeDistance(), copy(), and isEqual().
ValueInternalMap::IteratorState Json::ValueIteratorBase::map_
Definition at line 974 of file value.h.
Referenced by computeDistance(), copy(), and isEqual().
The documentation for this class was generated from the following files:
include/json/value.h
src/lib_json/json_valueiterator.inl
hosts this site. Send comments to:
Json-cpp Developers