JsonCpp - JSON data format manipulation library
JsonCpp project page JsonCpp home page
Json::ValueIterator Class Reference
Iterator for object and array value.
#include <json/value.h>
Inherits Json::ValueIteratorBase.
Public Types
typedef unsigned int size_t
typedef int difference_type
typedef Value & reference
typedef Value * pointer
typedef ValueIterator SelfType
Public Member Functions
ValueIterator ()
ValueIterator (const ValueConstIterator &other)
ValueIterator (const ValueIterator &other)
SelfType & operator= (const SelfType &other)
SelfType operator++ (int)
SelfType operator-- (int)
SelfType & operator-- ()
SelfType & operator++ ()
reference operator* () const
Friends
class Value
Detailed Description
Iterator for object and array value.
Definition at line 1041 of file value.h.
Member Typedef Documentation
typedef int Json::ValueIterator::difference_type
Reimplemented from Json::ValueIteratorBase.
Definition at line 1046 of file value.h.
typedef Value* Json::ValueIterator::pointer
Definition at line 1048 of file value.h.
typedef Value& Json::ValueIterator::reference
Definition at line 1047 of file value.h.
typedef ValueIterator Json::ValueIterator::SelfType
Reimplemented from Json::ValueIteratorBase.
Definition at line 1049 of file value.h.
typedef unsigned int Json::ValueIterator::size_t
Reimplemented from Json::ValueIteratorBase.
Definition at line 1045 of file value.h.
Constructor & Destructor Documentation
Json::ValueIterator::ValueIterator ()
Definition at line 260 of file json_valueiterator.inl.
Json::ValueIterator::ValueIterator (const ValueConstIterator & other)
Definition at line 282 of file json_valueiterator.inl.
Json::ValueIterator::ValueIterator (const ValueIterator & other)
Definition at line 287 of file json_valueiterator.inl.
Member Function Documentation
reference Json::ValueIterator::operator* () const [inline]
Definition at line 1093 of file value.h.
References Json::ValueIteratorBase::deref().
SelfType& Json::ValueIterator::operator++ () [inline]
Definition at line 1087 of file value.h.
References Json::ValueIteratorBase::increment().
SelfType Json::ValueIterator::operator++ (int) [inline]
Definition at line 1067 of file value.h.
SelfType& Json::ValueIterator::operator-- () [inline]
Definition at line 1081 of file value.h.
References Json::ValueIteratorBase::decrement().
SelfType Json::ValueIterator::operator-- (int) [inline]
Definition at line 1074 of file value.h.
ValueIterator & Json::ValueIterator::operator= (const SelfType & other)
Definition at line 293 of file json_valueiterator.inl.
References Json::ValueIteratorBase::copy().
Friends And Related Function Documentation
friend class Value [friend]
Definition at line 1043 of file value.h.
The documentation for this class was generated from the following files:
include/json/value.h
src/lib_json/json_valueiterator.inl
hosts this site. Send comments to:
Json-cpp Developers